Recover from ImportError when loading a registry.
This is necessary to avoid a dependency on testtools, because the --parallel
option to the selftest command requires bzrlib.tests.parallel_registry which
will try to initialize the tests package, causing an error without testtools:

ImportError: No module named testtools